=begin
#Permit.io API

# Authorization as a service 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'date'
require 'time'

module OpenapiClient
  class AttributeType
    BOOL = "bool".freeze
    NUMBER = "number".freeze
    STRING = "string".freeze
    TIME = "time".freeze
    ARRAY = "array".freeze
    JSON = "json".freeze

    def self.all_vars
      @all_vars ||= [BOOL, NUMBER, STRING, TIME, ARRAY, JSON].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AttributeType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AttributeType"
    end
  end
end
