=begin
#Permit.io API

# Authorization as a service 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'date'
require 'time'

module OpenapiClient
  class OnboardingStep
    CREATE_ORGANIZATION = "create_organization".freeze
    CREATE_PROJECT = "create_project".freeze
    CREATE_RESOURCE = "create_resource".freeze
    CREATE_ACTIONS = "create_actions".freeze
    ASSIGN_PERMISSIONS = "assign_permissions".freeze
    ASSIGN_USER_ROLES = "assign_user_roles".freeze
    CONNECT_SDK = "connect_sdk".freeze
    DONE = "done".freeze

    def self.all_vars
      @all_vars ||= [CREATE_ORGANIZATION, CREATE_PROJECT, CREATE_RESOURCE, CREATE_ACTIONS, ASSIGN_PERMISSIONS, ASSIGN_USER_ROLES, CONNECT_SDK, DONE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if OnboardingStep.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #OnboardingStep"
    end
  end
end
