=begin
#Permit.io API

# Authorization as a service 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AuditElementsDataApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuditElementsDataApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AuditElementsDataApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuditElementsDataApi' do
    it 'should create an instance of AuditElementsDataApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AuditElementsDataApi)
    end
  end

  # unit tests for elements_list_audit_logs
  # List audit logs
  # Lists audit logs for for specific elements config (tenant scope)
  # @param proj_id Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
  # @param env_id Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
  # @param elements_config_id Either the unique id of the elements_config, or the URL-friendly key of the elements_config (i.e: the \&quot;slug\&quot;).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search Text search for the email field
  # @option opts [Integer] :page Page number of the results to fetch, starting at 1.
  # @option opts [Integer] :per_page The number of results per page (max 100).
  # @return [PaginatedResultAuditLog]
  describe 'elements_list_audit_logs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
