=begin
#Permit.io API

# Authorization as a service 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DecisionLogsIngressApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DecisionLogsIngressApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DecisionLogsIngressApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DecisionLogsIngressApi' do
    it 'should create an instance of DecisionLogsIngressApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DecisionLogsIngressApi)
    end
  end

  # unit tests for insert_opa_decision_logs
  # OPA Decision Logs Ingress
  # This ingress endpoint captures OPA decision logs.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'insert_opa_decision_logs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
