=begin
#Permit.io API

# Authorization as a service 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::DummyEngineModel
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::DummyEngineModel do
  let(:instance) { OpenapiClient::DummyEngineModel.new }

  describe 'test an instance of DummyEngineModel' do
    it 'should create an instance of DummyEngineModel' do
      expect(instance).to be_instance_of(OpenapiClient::DummyEngineModel)
    end
  end
  describe 'test attribute "engine"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "timestamp"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
