=begin
#Permit.io API

# Authorization as a service 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::Engine
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::Engine do
  let(:instance) { OpenapiClient::Engine.new }

  describe 'test an instance of Engine' do
    it 'should create an instance of Engine' do
      expect(instance).to be_instance_of(OpenapiClient::Engine)
    end
  end
end
