=begin
#Permit.io API

# Authorization as a service 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PDPState
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PDPState do
  let(:instance) { OpenapiClient::PDPState.new }

  describe 'test an instance of PDPState' do
    it 'should create an instance of PDPState' do
      expect(instance).to be_instance_of(OpenapiClient::PDPState)
    end
  end
  describe 'test attribute "api_version"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
