=begin
#Permit.io API

# Authorization as a service 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ResourceId
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ResourceId do
  let(:instance) { OpenapiClient::ResourceId.new }

  describe 'test an instance of ResourceId' do
    it 'should create an instance of ResourceId' do
      expect(instance).to be_instance_of(OpenapiClient::ResourceId)
    end
  end
end
