name: Build and Publish Permit SDK Gem

on:
  release:
    types: [created]


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build gem
        run: |
          sed -i "s/<TAG>/${{ env.TAG_NAME }}/g" permit-sdk.gemspec
          gem build permit-sdk

      - name: Publish gem
        run: |
          gem push permit-sdk-${{ env.TAG_NAME }}.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
